export const CART_ACTION_TYPES = {
    "ADD_CART_ITEM":"ADD_CART_ITEM",
    "DECREMENT_CART_ITEM":"DECREMENT_CART_ITEM",
    "REMOVE_CART_ITEM":"REMOVE_CART_ITEM",
    "IS_CART_SHOWN": "IS_CART_SHOWN"

}